"""add shortlink tables

Revision ID: f3e01c164429
Revises: fe72156621c9
Create Date: 2026-04-23 17:12:24.198463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e01c164429'
down_revision: Union[str, None] = 'fe72156621c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fcm_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fcm_token')
    # ### end Alembic commands ###
